_base_: '../../config/default_local.yaml'

data:
  batch_size: 64
  dataset:
    meta:
      imagenetv2-c:
        type: img_classification
        path: 'path'
        corruptions: ['brightness', 'contrast', 'defocus_blur', 'elastic_transform', 'fog',
                      'frost', 'gaussian_noise', 'glass_blur', 'impulse_noise', 'jpeg_compression',
                      'motion_blur', 'pixelate', 'shot_noise', 'snow', 'zoom_blur']

        severities: [5]
    ttt:
      - imagenetv2-c

model:
  image:
    encoder:
      name: 'vit-b'
      size: 224
      patch_size: 16
      embeddings: 768
      layer: 12
      head: 12
    decoder:
      layer: 8
      head: 16
      embeddings: 512
  text:
    encoder:
      name: 'distilbert-base-uncased' 
      pretrained: true
      trainable: false
      embeddings: 768
  clip:
    projection: 256
    dropout: 0.1
    temperature: 1
  mae:
    mask_ratio: 0.75
  loss:
    alpha: 1
  peft:
    name: 'lora'
    r: 4
    alpha_r_scale: 2
    target_modules: ["k_proj", "v_proj", "q_proj", "out_proj"]
    dropout: 0.01

train:
  start_epoch: 0
  epochs: 3
  warmup_epochs: 2
  lr: 1e-4
  weight_decay: 0.05
  warmup_lr: 1e-6
  min_lr: 1e-7
  clip_grad: 0.1

  lr_scheduler:
    name: cosine

ttt:
  lr: 1e-3
  weight_decay: 0.2
  batch_size: 128
  epochs: 10
  optimizer: 'sgd'
  run_freq: 3

world_size: 1

reconst: 'feature'
wandb_project: 'mae_clip_lora_finetuning'
output: './output'
