_base_: './default_local.yaml'

data:
  batch_size: 64
  dataset:
    meta:
      imagenet:
        type: img_classification
        path: '/home/ykojima/dataset/imagenet'
        classes: 'imagenet'
        prompt: 'ensemble'
      imagenet_a:
        type: img_classification
        path: '/home/ykojima/dataset/imagenet-a'
        classes: 'imagenet_a'
        prompt: 'ensemble'
      imagenetv2:
        type: img_classification
        # path: '/path/to/dataset'
        path: '/home/ykojima/dataset/imagenetv2-c/original/0'
        classes: 'imagenet'
        prompt: 'ensemble'
      imagenet_r:
        type: img_classification
        # path: '/path/to/dataset'
        path: '/home/ykojima/dataset/imagenet-r'
        classes: 'imagenet_r'
        prompt: 'ensemble'
      imagenet_sketch:
        type: img_classification
        # path: '/path/to/dataset'
        path: '/home/ykojima/dataset/sketch'
        classes: 'imagenet'
        prompt: 'ensemble'

      flower102:
        type: img_classification
        path: '/home/ykojima/dataset/oxford_flowers/jpg'
        label: '/home/ykojima/dataset/oxford_flowers/split_zhou_OxfordFlowers.json'
        classes: 'flower102'
        prompt: 'ensemble'
      food101:
        type: img_classification
        path: '/home/ykojima/dataset/food-101/images'
        label: '/home/ykojima/dataset/food-101/split_zhou_Food101.json'
        classes: 'food101'
        prompt: 'ensemble'
      dtd:
        type: img_classification
        path: '/home/ykojima/dataset/dtd/images'
        label: '/home/ykojima/dataset/dtd/split_zhou_DescribableTextures.json'
        classes: 'dtd'
        prompt: 'ensemble'
      pets:
        type: img_classification
        path: '/home/ykojima/dataset/oxford_pets/images'
        label: '/home/ykojima/dataset/oxford_pets/split_zhou_OxfordPets.json'
        classes: 'pets'
        prompt: 'ensemble'
      sun397:
        type: img_classification
        path: '/home/ykojima/dataset/sun397/SUN397'
        label: '/home/ykojima/dataset/sun397/split_zhou_SUN397.json'
        classes: 'sun397'
        prompt: 'ensemble'
      caltech101:
        type: img_classification
        path: '/home/ykojima/dataset/caltech-101/101_ObjectCategories'
        label: '/home/ykojima/dataset/caltech-101/split_zhou_Caltech101.json'
        classes: 'caltech101'
        prompt: 'ensemble'
      ucf101:
        type: img_classification
        path: '/home/ykojima/dataset/ucf101/UCF-101-midframes'
        label: '/home/ykojima/dataset/ucf101/split_zhou_UCF101.json'
        classes: 'ucf101'
        prompt: 'ensemble'
      cars:
        type: img_classification
        path: '/home/ykojima/dataset/stanford_cars'
        label: '/home/ykojima/dataset/stanford_cars/split_zhou_StanfordCars.json'
        classes: 'cars'
        prompt: 'ensemble'
      eurosat:
        type: img_classification
        path: '/home/ykojima/dataset/eurosat/2750'
        label: '/home/ykojima/dataset/eurosat/split_zhou_EuroSAT.json'
        classes: 'eurosat'
        prompt: 'ensemble'
      aircraft:
        type: img_classification
        path: '/home/ykojima/dataset/fgvc_aircraft'
        label: ''
        classes: 'aircraft'
        prompt: 'ensemble'
 
    # tta: ['imagenet', 'imagenet_a', 'imagenetv2', 'imagenet_r', 'imagenet_sketch']
    # tta: ['flower102', 'dtd', 'pets', 'cars', 'ucf101', 'caltech101', 'food101', 'sun397', 'aircraft', 'eurosat']
    tta: ['caltech101']
    train: ['gcc3m_005']

model:
  image:
    encoder:
      name: 'vit-b'
      size: 224
      patch_size: 16
      embeddings: 768
      layer: 12
      head: 12
    decoder:
      layer: 8
      head: 16
      embeddings: 512
  text:
    encoder:
      name: 'distilbert-base-uncased' 
      pretrained: true
      trainable: false
      embeddings: 768
  clip:
    projection: 256
    dropout: 0.1
    temperature: 1
  mae:
    mask_ratio: 0.75
  loss:
    alpha: 1
  peft:
    name: 'lora'
    r: 4
    alpha_r_scale: 2
    target_modules: ["k_proj", "v_proj", "q_proj", "out_proj"]
    dropout: 0.01
    layers_to_transform: [0,1,2,3,4,5,6,7,8,9,10,11]

train:
  start_epoch: 0
  epochs: 1
  warmup_epochs: 2
  lr: 1e-4
  weight_decay: 0.05
  warmup_lr: 1e-6
  min_lr: 1e-7
  clip_grad: 0.1

  lr_scheduler:
    name: cosine

tta:
  mae:
    lr: 1e-3
    weight_decay: 0.2
    batch_size: 64
    epochs: 1
    optimizer: 'adam'
  tpt:
    lr: 5e-3
    batch_size: 64
    epochs: 1
  enable: ['mae']
  run_freq: 1

world_size: 1

reconst: 'feature'
wandb_project: 'test'
output: './output'
