_base_: './default_local.yaml'

data:
  batch_size: 64
  dataset:
    meta:
      imagenet:
        type: img_classification
        path: '/path/to/dataset'
        classes: 'imagenet'
        prompt: 'ensemble'
      imagenet_a:
        type: img_classification
        path: '/path/to/dataset'
        classes: 'imagenet_a'
        prompt: 'ensemble'
      imagenetv2:
        type: img_classification
        path: '/path/to/dataset'
        classes: 'imagenet'
        prompt: 'ensemble'
      imagenet_r:
        type: img_classification
        path: '/path/to/dataset'
        classes: 'imagenet_r'
        prompt: 'ensemble'
      imagenet_sketch:
        type: img_classification
        path: '/path/to/dataset'
        classes: 'imagenet'
        prompt: 'ensemble'
 
    tta: ['imagenet_a', 'imagenetv2', 'imagenet_r', 'imagenet_sketch']
    train: ['gcc3m_01']

model:
  image:
    encoder:
      name: 'vit-b'
      size: 224
      patch_size: 16
      embeddings: 768
      layer: 12
      head: 12
    decoder:
      layer: 8
      head: 16
      embeddings: 512
  text:
    encoder:
      name: 'distilbert-base-uncased' 
      pretrained: true
      trainable: false
      embeddings: 768
  clip:
    projection: 256
    dropout: 0.1
    temperature: 1
  mae:
    mask_ratio: 0.75
  loss:
    alpha: 1
  peft:
    name: 'lora'
    r: 4
    alpha_r_scale: 2
    target_modules: ["k_proj", "v_proj", "q_proj", "out_proj"]
    dropout: 0.01
    layers_to_transform: [0,1,2,3,4,5,6,7,8,9,10,11]

train:
  start_epoch: 0
  epochs: 1
  warmup_epochs: 2
  lr: 1e-4
  weight_decay: 0.05
  warmup_lr: 1e-6
  min_lr: 1e-7
  clip_grad: 0.1

  lr_scheduler:
    name: cosine

tta:
  mae:
    lr: 1e-3
    weight_decay: 0.2
    batch_size: 128
    epochs: 1
    optimizer: 'adam'
  tpt:
    lr: 5e-3
    batch_size: 64
    epochs: 1
  enable: ['mae', 'tpt']
  run_freq: 1

world_size: 1

reconst: 'feature'
wandb_project: 'test'
output: './output'
